# WhiteVPN — Конфигурация белого списка
# telegram=1 — включён, telegram=0 — выключен
# youtube=1 — включён, youtube=0 — выключен
# custom=1 — включён, custom=0 — выключен

telegram=1
youtube=1
custom=1
